name: Build Sealer
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build sealer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build docker container
        run: |
          cp ./genesis.json sealer/genesis.json

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: f2fmarket/ethereum-node
          tags: sealer
          path: sealer/
